# Generated by Django 3.1.3 on 2020-11-22 02:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_auto_20201122_0219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cards', to='games.game'),
        ),
        migrations.AlterField(
            model_name='cluerelation',
            name='game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='known_relations', to='games.game'),
        ),
        migrations.AlterField(
            model_name='player',
            name='game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='players', to='games.game'),
        ),
    ]
