# Generated by Django 3.1.3 on 2020-11-22 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_auto_20201122_0302'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Card',
            new_name='GameCard',
        ),
        migrations.RemoveField(
            model_name='cluerelation',
            name='card_set',
        ),
        migrations.AddField(
            model_name='cluerelation',
            name='cards',
            field=models.ManyToManyField(related_name='relations_containing', to='games.GameCard'),
        ),
        migrations.AlterField(
            model_name='cluerelation',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations_containing', to='games.player'),
        ),
    ]
