services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=cluesolver
      - POSTGRES_USER=cluesolver
      - POSTGRES_PASSWORD=cluesolver
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "cluesolver"]
      interval: 10s
      timeout: 5s
      retries: 5

  webapp:
    build: .
    command: gunicorn -b 0.0.0.0:8000 cluesolver.wsgi
    environment:
      - DOCKER_DEV=true
    volumes:
      - static-content:/code/cluesolver/static
    depends_on:
      db:
        condition: service_healthy

  web:
    build: ./web
    volumes:
      - static-content:/static
    ports:
      - "8080:80"
    depends_on:
      - webapp

volumes:
  static-content:
