# Generated by Django 3.1.3 on 2020-11-22 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='card',
            name='game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='games.game'),
        ),
        migrations.AddField(
            model_name='cluerelation',
            name='game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='known_relations', to='games.game'),
        ),
        migrations.AddField(
            model_name='player',
            name='game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='players', to='games.game'),
        ),
        migrations.AlterUniqueTogether(
            name='card',
            unique_together={('name', 'game')},
        ),
        migrations.AlterUniqueTogether(
            name='player',
            unique_together={('name', 'game')},
        ),
    ]
